controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login:
    path: /api/login
    methods: POST
    defaults:
        _controller: App\Controller\SecurityController::login

api_login_check:
    path: /api/login_check
    methods: ['POST']

api_me:
    path: /api/me
    methods: GET
    defaults:
        _controller: App\Controller\SecurityController::me

api_week_meals:
    path: /api/week-meals
    methods: GET
    defaults:
        _controller: App\Controller\WeekMealController::getWeekMeals

api_shopping_list_generate:
    path: /api/shopping-list/generate/{weekStart}
    methods: POST
    defaults:
        _controller: App\Controller\ShoppingListController::generateShoppingList

api_shopping_list_get:
    path: /api/shopping-list/{weekStart}
    methods: GET
    defaults:
        _controller: App\Controller\ShoppingListController::getShoppingList

api_shopping_item_toggle:
    path: /api/shopping-list/item/{id}/toggle
    methods: PATCH
    defaults:
        _controller: App\Controller\ShoppingListController::toggleShoppingItem
